# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sjy-restaurant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sjy-restaurant
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
  target 'sjy-restaurantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sjy-restaurantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
